# FILE: base/booking-app/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app-deployment
  labels:
    app: booking-app
spec:
  replicas: 2 # Pre vysokú dostupnosť
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      # Pravidlo Antiaffinity na rozloženie Podov medzi rôzne Node/VM
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: booking-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: placeholder/booking-app-container
        # Placeholder Image, ktorý prepíšeme v overlays/prod
        image: placeholder/bookingapp:lates
        ports:
        - containerPort: 8081 # Predpokladaný iný port, ako pre Insurance App
        
        # --- Kľúčové pre stabilitu (Resource Limits) ---
        resources:
          requests:
            memory: "64Mi" 
            cpu: "100m"
          limits:
            memory: "192Mi" 
            cpu: "500m"
        # ---------------------------------------------
        
        env:
        # --- ENV pre PostgreSQL Secret (postgresql-secret) ---
        - name: DATABASE_HOST
          value: postgresql-service # Service pre PostgreSQL
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-password
        - name: DATABASE_NAME
          value: booking_db
        # ... Ak by Booking App potrebovala Mail Secret, pridali by ste ho sem.
        # Pre jednoduchosť predpokladáme, že ho nepotrebuje.
