apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app-deployment
  namespace: booking-app       # ⬅️ odporúčané (rovnako ako insurance)
  labels:
    app: booking-app

spec:
  replicas: 1               # ⬅️ k3s / 1-node cluster

  selector:
    matchLabels:
      app: booking-app

  template:
    metadata:
      labels:
        app: booking-app

    spec:
      imagePullSecrets:
        - name: ghcr-login-secret

      terminationGracePeriodSeconds: 30

      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgresql-service 5432; do
                echo "Waiting for PostgreSQL..."
                sleep 3
              done

      containers:
        - name: booking-app-container
          image: ghcr.io/gloziksoft/booking-app:prod
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              name: http

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql-service:5432/booking_db

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-user

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-password

            - name: SPRING_PROFILES_ACTIVE
              value: prod

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
