apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app-deployment
  labels:
    app: booking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      # OPRAVA 1: Zmena na 'preferred', aby oba pody bežali na tvojom ASUS notebooku
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: booking-app
              topologyKey: "kubernetes.io/hostname"

      # OPRAVA 2: Musíš povedať Deploymentu, aby použil ten secret, čo už máš v klastri
      imagePullSecrets:
        - name: ghcr-login-secret

      containers:
      - name: booking-app-container
        image: bookingapp:latest # Kustomize toto nahradí tvojím ghcr.io obrazom
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "128Mi" # Znížené, aby sa v klastri uvoľnilo miesto pre Postgres
            cpu: "100m"
          limits:
            memory: "512Mi" # Horná hranica, aby appka nezomrela pri štarte
            cpu: "500m"
        env:
        # Spring Boot štandardne hľadá tieto premenné pre DB pripojenie
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql-service:5432/booking_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-password
