# FILE: base/booking-app/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources: Definuje všetky základné manifesty, ktoré tvoria túto aplikáciu.
# Tieto súbory sú v rovnakom adresári (base/booking-app/).
resources:
  - deployment.yaml
  - service.yaml
  - db-service.yaml
  - postgresql-statefulset.yaml
  - secrets/postgresql-secret.yaml
