# FILE: base/booking-app/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: booking-app-service # Názov Service
  labels:
    app: booking-app
spec:
  # V Base používame ClusterIP. Externé vystavenie sa rieši v Overlay.
  type: ClusterIP 
  
  # Definuje, na ktoré Pody Service smeruje
  selector:
    app: booking-app 
  
  # Mapovanie portov
  ports:
      name: http
    - protocol: TCP
      port: 80         # Port Service
      targetPort: 8081 # Port kontajnera (definovaný v deployment.yaml)
