apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app-deployment
  labels:
    app: insurance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
    spec:
      # Povolenie na sťahovanie z tvojho GitHub Container Registry
      imagePullSecrets:
        - name: ghcr-login-secret
      
      # Affinity nastavené tak, aby preferovalo rôzne uzly, ale neblokovalo štart na jednom
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: insurance-app
              topologyKey: "kubernetes.io/hostname"

      containers:
      - name: insurance-app-container
        image: ghcr.io/gloziksoft/insuranceapp/insurance-app:latest
        ports:
        - containerPort: 8080
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "192Mi"
            cpu: "500m"
        
        env:
        # --- DATABÁZA ---
        # Spring Boot automaticky použije túto URL na pripojenie k MariaDB
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mariadb://mariadb-service:3306/insurance_db
        
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-user
        
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-password

        # --- EMAIL (SMTP) ---
        - name: SPRING_MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: smtp-host
              
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: smtp-password

        # --- DOPLNKOVÉ NASTAVENIA ---
        # Ak aplikácia pri štarte hovorí, že nemá aktívny profil, toto ho nastaví na "default" alebo "prod"
        - name: SPRING_PROFILES_ACTIVE
          value: default
