# FILE: base/insurance-app/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources: Definuje všetky základné manifesty, ktoré tvoria túto aplikáciu.
# Tieto súbory sú v rovnakom adresári (base/insurance-app/).
resources:
- deployment.yaml
- service.yaml
- mariadb-statefulset.yaml
- mariadb-secret.yaml # Váš pôvodný súbor mal názov mail-secret.yaml, ale predpokladám, že slúži pre DB heslo
- db-service.yaml
