apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
# ... (ďalšie zdroje pre app) ...

# Nastavenie, kde bude Kustomize vedieť, ktoré image meniť
images:
- name: <Docker_Username>/insuranceapp # Meno image bez tagu
  newName: <Gloziksoft>/insuranceapp # <--- OPRAVA TU
  newTag: latest
